### ISSUE TITLE
Clarification regarding "memory matrices"

### ISSUE THREAD

**Issue by Aryan-Satpathy** [steve-zeyu-zhang/MotionMamba#2]
Dear Authors,

Thank you for your excellent efforts.  I was finding it difficult to understand the role of Memory Matrices in the HTM module.

This step utilizes a hierarchically structured set of scans, $K =$ { $S^{2N_n−1}, S^{2N_n−1−1}, . . . , S^1$ }, in conjunction with a corresponding series of memory matrices { $A_1, . . . , A_k$ }. Each sub-SSM scan first applies a 1-D convolution to x, resulting in $x^\prime_o$. $x^\prime_o$ is then linearly projected to derive $B_o$, $C_o$, and $\Delta_o$. These projections $B_o$, $C_o$ use $\Delta_o$ to effect transformations in $A_o$ and $B_o$ , respectively. After executing a sequence of SSM scans { $SSM_{A_1,x}, SSM_{A_2,x}, . . . , SSM_{A_k ,x}$ }, a set of outputs { $O_1, . . . , O_k$ } is compiled.

I would appreciate it if you could provide some info regarding what the memory matrices { $A_1, . . . , A_k$ } do and how they are used by $SSM_{A_i,x}$.

**Comment by steve-zeyu-zhang** [comment]
Thank you for your interest. 

In the U-Net denoiser, the number of scans of the SSM in the HTM block decreases from the encoder to the latent block and then increases from the latent block to the decoder. 

Additionally, within each HTM, each SSM has its own evolution parameter $A$, also known as memory metrics. These memory metrics are not shared between SSMs. 

Therefore, $K = \{ S^{2N_n-1}, S^{2N_n-2}, \ldots, S^1 \}$ corresponds to a series of distinct memory matrices $\{ A_1, \ldots, A_k \}$.

Feel free to bring out more questions.

**Comment by Aryan-Satpathy** [comment]
Thanks, @steve-zeyu-zhang. This was helpful! I will mark this as closed now.
